### PR TITLE
feat(yandex): Support provider Yandex.Cloud

### PR DESCRIPTION
**Pull request by vasiliy-briginets**
Added support for baking Yandex Cloud images.

Proposal - https://github.com/spinnaker/governance/issues/166

### CODE REVIEW

**Comment by vasiliy-briginets** [comment]
@spinnaker/reviewers

**Comment by vasiliy-briginets** [comment]
@spinnaker/reviewers

**Comment by ajordens** [comment]
Not a rosco expert/user, there is a conflict that needs to be resolved prior to the workflow running. 

Nothing stands out here so I'll merge when the build passes.

**Comment by st8f** [comment]
> there is a conflict that needs to be resolved

Fixed it. Should be ok now.

**Review by mattgogerly — COMMENTED** [review]
What happened to the README file?

**Pull request closed without merging**
