### PR TITLE
Use sudo to run yum in packer templates.

### PR DESCRIPTION
**Pull request by duftler**
Configure ssh pseudo terminal to avoid 'sudo needs tty' error on centos.

### CODE REVIEW

**Comment by duftler** [comment]
@gardleopard Can you please review this PR?
I'm especially interested in verifying that it correctly bakes centos images on ec2.
@radkin please see if these changes enable your centos bake to complete ok.
Relates to https://github.com/spinnaker/spinnaker/issues/820.

**Comment by radkin** [comment]
The commands look correct to me, thanks! :+1:

**Comment by gardleopard** [comment]
@duftler  this is not working and it is more wide than centos. The scope for this is all builders that is not running as root. It fails here https://github.com/duftler/rosco/blob/centos-tweaks/rosco-web/config/packer/install_packages.sh#L50.

I realise that the changes we have done to install packages require that you are root. I will do a simple test with amazon linux, centos and trusty to verify this. In example https://github.com/duftler/rosco/blob/centos-tweaks/rosco-web/config/packer/install_packages.sh#L22 should also fail if you are not root.

**Comment by gardleopard** [comment]
Ive verified that this works if you merge the changes in https://github.com/duftler/rosco/pull/1

centos
```
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 56f1ba63-6ddb-6779-4055-854f770d261b
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-a204b028
==> amazon-ebs: Waiting for instance (i-a204b028) to become ready...
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Pausing 30s before the next provisioner...
==> amazon-ebs: Provisioning with shell script: /opt/rosco/config/packer/install_packages.sh
    amazon-ebs: repository=
    amazon-ebs: package_type=rpm
    amazon-ebs: packages=httpd
    amazon-ebs: upgrade=
    amazon-ebs: Loaded plugins: fastestmirror
    amazon-ebs: base             | 3.6 kB     00:00
    amazon-ebs: extras           | 3.4 kB     00:00
    amazon-ebs: updates          | 3.4 kB     00:00
    amazon-ebs: (1/4): base/7/x86_ | 155 kB   00:00
    amazon-ebs: (2/4): extras/7/x8 | 101 kB   00:00
    amazon-ebs: (3/4): updates/7/x | 3.2 MB   00:00
    amazon-ebs: (4/4): base/7/x86_ | 5.3 MB   00:01
    amazon-ebs: Determining fastest mirrors
    amazon-ebs: * base: repo.bigstepcloud.com
    amazon-ebs: * extras: mirrors.clouvider.net
    amazon-ebs: * updates: mirrors.vooservers.com
    amazon-ebs: Resolving Dependencies
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package httpd.x86_64 0:2.4.6-40.el7.centos will be installed
    amazon-ebs: --> Processing Dependency: httpd-tools = 2.4.6-40.el7.centos for package: httpd-2.4.6-40.el7.centos.x86_64
    amazon-ebs: --> Processing Dependency: /etc/mime.types for package: httpd-2.4.6-40.el7.centos.x86_64
    amazon-ebs: --> Processing Dependency: libaprutil-1.so.0()(64bit) for package: httpd-2.4.6-40.el7.centos.x86_64
    amazon-ebs: --> Processing Dependency: libapr-1.so.0()(64bit) for package: httpd-2.4.6-40.el7.centos.x86_64
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package apr.x86_64 0:1.4.8-3.el7 will be installed
    amazon-ebs: ---> Package apr-util.x86_64 0:1.5.2-6.el7 will be installed
    amazon-ebs: ---> Package httpd-tools.x86_64 0:2.4.6-40.el7.centos will be installed
    amazon-ebs: ---> Package mailcap.noarch 0:2.1.41-2.el7 will be installed
    amazon-ebs: --> Finished Dependency Resolution
    amazon-ebs:
    amazon-ebs: Dependencies Resolved
    amazon-ebs:
    amazon-ebs: ========================================
    amazon-ebs: Package Arch   Version      Repository
    amazon-ebs: Size
    amazon-ebs: ========================================
    amazon-ebs: Installing:
    amazon-ebs: httpd   x86_64 2.4.6-40.el7.centos
    amazon-ebs: base 2.7 M
    amazon-ebs: Installing for dependencies:
    amazon-ebs: apr     x86_64 1.4.8-3.el7  base 103 k
    amazon-ebs: apr-util
    amazon-ebs: x86_64 1.5.2-6.el7  base  92 k
    amazon-ebs: httpd-tools
    amazon-ebs: x86_64 2.4.6-40.el7.centos
    amazon-ebs: base  82 k
    amazon-ebs: mailcap noarch 2.1.41-2.el7 base  31 k
    amazon-ebs:
    amazon-ebs: Transaction Summary
    amazon-ebs: ========================================
    amazon-ebs: Install  1 Package (+4 Dependent packages)
    amazon-ebs:
    amazon-ebs: Total download size: 3.0 M
    amazon-ebs: Installed size: 10 M
    amazon-ebs: Downloading packages:
    amazon-ebs: warning: /var/cache/yum/x86_64/7/base/packages/apr-util-1.5.2-6.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
    amazon-ebs: Public key for apr-util-1.5.2-6.el7.x86_64.rpm is not installed
    amazon-ebs: (1/5): apr-util-1. |  92 kB   00:00
    amazon-ebs: (2/5): apr-1.4.8-3 | 103 kB   00:00
    amazon-ebs: (3/5): httpd-tools |  82 kB   00:00
    amazon-ebs: (4/5): mailcap-2.1 |  31 kB   00:00
    amazon-ebs: (5/5): httpd-2.4.6 | 2.7 MB   00:00
    amazon-ebs: ----------------------------------------
    amazon-ebs: Total      3.4 MB/s | 3.0 MB  00:00
    amazon-ebs: Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    amazon-ebs: Importing GPG key 0xF4A80EB5:
    amazon-ebs: Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
    amazon-ebs: Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
    amazon-ebs: Package    : centos-release-7-2.1511.el7.centos.2.10.x86_64 (installed)
    amazon-ebs: From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    amazon-ebs: Running transaction check
    amazon-ebs: Running transaction test
    amazon-ebs: Transaction test succeeded
    amazon-ebs: Running transaction
    amazon-ebs:   Installing : apr-1.4.8-3.el7.x8   1/5
    amazon-ebs:   Installing : apr-util-1.5.2-6.e   2/5
    amazon-ebs:   Installing : httpd-tools-2.4.6-   3/5
    amazon-ebs:   Installing : mailcap-2.1.41-2.e   4/5
    amazon-ebs:   Installing : httpd-2.4.6-40.el7   5/5
    amazon-ebs: Verifying  : httpd-2.4.6-40.el7   1/5
    amazon-ebs: Verifying  : apr-1.4.8-3.el7.x8   2/5
    amazon-ebs: Verifying  : mailcap-2.1.41-2.e   3/5
    amazon-ebs: Verifying  : httpd-tools-2.4.6-   4/5
    amazon-ebs: Verifying  : apr-util-1.5.2-6.e   5/5
    amazon-ebs:
    amazon-ebs: Installed:
    amazon-ebs: httpd.x86_64 0:2.4.6-40.el7.centos
    amazon-ebs:
    amazon-ebs: Dependency Installed:
    amazon-ebs: apr.x86_64 0:1.4.8-3.el7
    amazon-ebs: apr-util.x86_64 0:1.5.2-6.el7
    amazon-ebs: httpd-tools.x86_64 0:2.4.6-40.el7.centos
    amazon-ebs: mailcap.noarch 0:2.1.41-2.el7
    amazon-ebs:
    amazon-ebs: Complete!
==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating the AMI: test-centos-all-1458682467630-centos
    amazon-ebs: AMI: ami-b9af2bca
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Adding tags to AMI (ami-b9af2bca)...
    amazon-ebs: Adding tag: "appversion": ""
    amazon-ebs: Adding tag: "build_host": ""
==> amazon-ebs: Tagging snapshot: snap-bcd70093
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Destroying volume (vol-dfc1642d)...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

eu-west-1: ami-b9af2bca
Build 'dae5a0b0-f075-11e5-8bc8-02ff97ff5883' finished. State: COMPLETED. Result: SUCCESS
```

ubuntu
```
==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 56f1ba7e-a089-e0cd-ee82-36c18697fe38
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-9306b219
==> amazon-ebs: Waiting for instance (i-9306b219) to become ready...
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Pausing 30s before the next provisioner...
==> amazon-ebs: Provisioning with shell script: /opt/rosco/config/packer/install_packages.sh
    amazon-ebs: repository=
    amazon-ebs: package_type=deb
    amazon-ebs: packages=apache2
    amazon-ebs: upgrade=
    amazon-ebs: Ign http://eu-west-1.ec2.archive.ubuntu.com trusty InRelease
    amazon-ebs: Get:1 http://eu-west-1.ec2.archive.ubuntu.com trusty-updates InRelease [65.9 kB]
    amazon-ebs: Hit http://eu-west-1.ec2.archive.ubuntu.com trusty Release.gpg
    amazon-ebs: Hit http://eu-west-1.ec2.archive.ubuntu.com trusty Release
    amazon-ebs: Get:2 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
    amazon-ebs: Get:3 http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/main Sources [264 kB]
    amazon-ebs: Get:4 http://security.ubuntu.com trusty-security/main Sources [109 kB]
    amazon-ebs: Get:5 http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/universe Sources [151 kB]
    amazon-ebs: Get:6 http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/main amd64 Packages [730 kB]
    amazon-ebs: Get:7 http://security.ubuntu.com trusty-security/universe Sources [34.1 kB]
    amazon-ebs: Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [447 kB]
    amazon-ebs: Get:9 http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/universe amd64 Packages [339 kB]
    amazon-ebs: Get:10 http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/main Translation-en [367 kB]
    amazon-ebs: Get:11 http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/universe Translation-en [182 kB]
    amazon-ebs: Get:12 http://eu-west-1.ec2.archive.ubuntu.com trusty/main Sources [1,064 kB]
    amazon-ebs: Get:13 http://security.ubuntu.com trusty-security/universe amd64 Packages [125 kB]
    amazon-ebs: Get:14 http://security.ubuntu.com trusty-security/main Translation-en [244 kB]
    amazon-ebs: Get:15 http://eu-west-1.ec2.archive.ubuntu.com trusty/universe Sources [6,399 kB]
    amazon-ebs: Get:16 http://security.ubuntu.com trusty-security/universe Translation-en [73.9 kB]
    amazon-ebs: Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/main amd64 Packages
    amazon-ebs: Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/universe amd64 Packages
    amazon-ebs: Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/main Translation-en
    amazon-ebs: Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/universe Translation-en
    amazon-ebs: Ign http://eu-west-1.ec2.archive.ubuntu.com trusty/main Translation-en_US
    amazon-ebs: Ign http://eu-west-1.ec2.archive.ubuntu.com trusty/universe Translation-en_US
    amazon-ebs: Fetched 10.7 MB in 8s (1,247 kB/s)
    amazon-ebs: Reading package lists... Done
    amazon-ebs: Reading package lists... Done
    amazon-ebs: Building dependency tree
    amazon-ebs: Reading state information... Done
    amazon-ebs: The following extra packages will be installed:
    amazon-ebs: apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
    amazon-ebs: libaprutil1-ldap ssl-cert
    amazon-ebs: Suggested packages:
    amazon-ebs: apache2-doc apache2-suexec-pristine apache2-suexec-custom apache2-utils
    amazon-ebs: openssl-blacklist
    amazon-ebs: The following NEW packages will be installed:
    amazon-ebs: apache2 apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
    amazon-ebs: libaprutil1-ldap ssl-cert
    amazon-ebs: 0 upgraded, 8 newly installed, 0 to remove and 160 not upgraded.
    amazon-ebs: Need to get 1,283 kB of archives.
    amazon-ebs: After this operation, 5,348 kB of additional disk space will be used.
    amazon-ebs: Get:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main libapr1 amd64 1.5.0-1 [85.1 kB]
    amazon-ebs: Get:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main libaprutil1 amd64 1.5.3-1 [76.4 kB]
    amazon-ebs: Get:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main libaprutil1-dbd-sqlite3 amd64 1.5.3-1 [10.5 kB]
    amazon-ebs: Get:4 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main libaprutil1-ldap amd64 1.5.3-1 [8,634 B]
    amazon-ebs: Get:5 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main apache2-bin amd64 2.4.7-1ubuntu4.9 [839 kB]
    amazon-ebs: Get:6 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main apache2-data all 2.4.7-1ubuntu4.9 [160 kB]
    amazon-ebs: Get:7 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main apache2 amd64 2.4.7-1ubuntu4.9 [87.5 kB]
    amazon-ebs: Get:8 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main ssl-cert all 1.0.33 [16.6 kB]
    amazon-ebs: Fetched 1,283 kB in 0s (2,644 kB/s)
    amazon-ebs: Preconfiguring packages ...
    amazon-ebs: Selecting previously unselected package libapr1:amd64.
    amazon-ebs: (Reading database ... 51120 files and directories currently installed.)
    amazon-ebs: Preparing to unpack .../libapr1_1.5.0-1_amd64.deb ...
    amazon-ebs: Unpacking libapr1:amd64 (1.5.0-1) ...
    amazon-ebs: Selecting previously unselected package libaprutil1:amd64.
    amazon-ebs: Preparing to unpack .../libaprutil1_1.5.3-1_amd64.deb ...
    amazon-ebs: Unpacking libaprutil1:amd64 (1.5.3-1) ...
    amazon-ebs: Selecting previously unselected package libaprutil1-dbd-sqlite3:amd64.
    amazon-ebs: Preparing to unpack .../libaprutil1-dbd-sqlite3_1.5.3-1_amd64.deb ...
    amazon-ebs: Unpacking libaprutil1-dbd-sqlite3:amd64 (1.5.3-1) ...
    amazon-ebs: Selecting previously unselected package libaprutil1-ldap:amd64.
    amazon-ebs: Preparing to unpack .../libaprutil1-ldap_1.5.3-1_amd64.deb ...
    amazon-ebs: Unpacking libaprutil1-ldap:amd64 (1.5.3-1) ...
    amazon-ebs: Selecting previously unselected package apache2-bin.
    amazon-ebs: Preparing to unpack .../apache2-bin_2.4.7-1ubuntu4.9_amd64.deb ...
    amazon-ebs: Unpacking apache2-bin (2.4.7-1ubuntu4.9) ...
    amazon-ebs: Selecting previously unselected package apache2-data.
    amazon-ebs: Preparing to unpack .../apache2-data_2.4.7-1ubuntu4.9_all.deb ...
    amazon-ebs: Unpacking apache2-data (2.4.7-1ubuntu4.9) ...
    amazon-ebs: Selecting previously unselected package apache2.
    amazon-ebs: Preparing to unpack .../apache2_2.4.7-1ubuntu4.9_amd64.deb ...
    amazon-ebs: Unpacking apache2 (2.4.7-1ubuntu4.9) ...
    amazon-ebs: Selecting previously unselected package ssl-cert.
    amazon-ebs: Preparing to unpack .../ssl-cert_1.0.33_all.deb ...
    amazon-ebs: Unpacking ssl-cert (1.0.33) ...
    amazon-ebs: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
    amazon-ebs: Processing triggers for ureadahead (0.100.0-16) ...
    amazon-ebs: Processing triggers for ufw (0.34~rc-0ubuntu2) ...
    amazon-ebs: Setting up libapr1:amd64 (1.5.0-1) ...
    amazon-ebs: Setting up libaprutil1:amd64 (1.5.3-1) ...
    amazon-ebs: Setting up libaprutil1-dbd-sqlite3:amd64 (1.5.3-1) ...
    amazon-ebs: Setting up libaprutil1-ldap:amd64 (1.5.3-1) ...
    amazon-ebs: Setting up apache2-bin (2.4.7-1ubuntu4.9) ...
    amazon-ebs: Setting up apache2-data (2.4.7-1ubuntu4.9) ...
    amazon-ebs: Setting up apache2 (2.4.7-1ubuntu4.9) ...
    amazon-ebs: Enabling module mpm_event.
    amazon-ebs: Enabling module authz_core.
    amazon-ebs: Enabling module authz_host.
    amazon-ebs: Enabling module authn_core.
    amazon-ebs: Enabling module auth_basic.
    amazon-ebs: Enabling module access_compat.
    amazon-ebs: Enabling module authn_file.
    amazon-ebs: Enabling module authz_user.
    amazon-ebs: Enabling module alias.
    amazon-ebs: Enabling module dir.
    amazon-ebs: Enabling module autoindex.
    amazon-ebs: Enabling module env.
    amazon-ebs: Enabling module mime.
    amazon-ebs: Enabling module negotiation.
    amazon-ebs: Enabling module setenvif.
    amazon-ebs: Enabling module filter.
    amazon-ebs: Enabling module deflate.
    amazon-ebs: Enabling module status.
    amazon-ebs: Enabling conf charset.
    amazon-ebs: Enabling conf localized-error-pages.
    amazon-ebs: Enabling conf other-vhosts-access-log.
    amazon-ebs: Enabling conf security.
    amazon-ebs: Enabling conf serve-cgi-bin.
    amazon-ebs: Enabling site 000-default.
    amazon-ebs: * Starting web server a  *he2
    amazon-ebs: Setting up ssl-cert (1.0.33) ...
    amazon-ebs: Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
    amazon-ebs: Processing triggers for ureadahead (0.100.0-16) ...
    amazon-ebs: Processing triggers for ufw (0.34~rc-0ubuntu2) ...
==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating the AMI: test-ubuntu-all-1458682494576-trusty
    amazon-ebs: AMI: ami-63b63210
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Adding tags to AMI (ami-63b63210)...
    amazon-ebs: Adding tag: "build_host": ""
    amazon-ebs: Adding tag: "appversion": ""
==> amazon-ebs: Tagging snapshot: snap-e42e75e0
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

eu-west-1: ami-63b63210
```

Amazon linux
```
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name...
==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 56f1bad7-ddda-a446-69a6-332821808c26
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
    amazon-ebs: Instance ID: i-4a05b1c0
==> amazon-ebs: Waiting for instance (i-4a05b1c0) to become ready...
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Pausing 30s before the next provisioner...
==> amazon-ebs: Provisioning with shell script: /opt/rosco/config/packer/install_packages.sh
    amazon-ebs: repository=
    amazon-ebs: package_type=rpm
    amazon-ebs: packages=httpd
    amazon-ebs: upgrade=
    amazon-ebs: Loaded plugins: priorities, update-motd,
    amazon-ebs: : upgrade-helper
    amazon-ebs: Resolving Dependencies
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package httpd.x86_64 0:2.2.31-1.7.amzn1 will be installed
    amazon-ebs: --> Processing Dependency: httpd-tools = 2.2.31-1.7.amzn1 for package: httpd-2.2.31-1.7.amzn1.x86_64
    amazon-ebs: --> Processing Dependency: apr-util-ldap for package: httpd-2.2.31-1.7.amzn1.x86_64
    amazon-ebs: --> Processing Dependency: libaprutil-1.so.0()(64bit) for package: httpd-2.2.31-1.7.amzn1.x86_64
    amazon-ebs: --> Processing Dependency: libapr-1.so.0()(64bit) for package: httpd-2.2.31-1.7.amzn1.x86_64
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package apr.x86_64 0:1.5.1-1.12.amzn1 will be installed
    amazon-ebs: ---> Package apr-util.x86_64 0:1.4.1-4.17.amzn1 will be installed
    amazon-ebs: ---> Package apr-util-ldap.x86_64 0:1.4.1-4.17.amzn1 will be installed
    amazon-ebs: ---> Package httpd-tools.x86_64 0:2.2.31-1.7.amzn1 will be installed
    amazon-ebs: --> Finished Dependency Resolution
    amazon-ebs:
    amazon-ebs: Dependencies Resolved
    amazon-ebs:
    amazon-ebs: ========================================
    amazon-ebs: Package       Arch   Version
    amazon-ebs: Repository
    amazon-ebs: Size
    amazon-ebs: ========================================
    amazon-ebs: Installing:
    amazon-ebs: httpd         x86_64 2.2.31-1.7.amzn1
    amazon-ebs: amzn-main 1.2 M
    amazon-ebs: Installing for dependencies:
    amazon-ebs: apr           x86_64 1.5.1-1.12.amzn1
    amazon-ebs: amzn-main 116 k
    amazon-ebs: apr-util      x86_64 1.4.1-4.17.amzn1
    amazon-ebs: amzn-main  87 k
    amazon-ebs: apr-util-ldap x86_64 1.4.1-4.17.amzn1
    amazon-ebs: amzn-main  17 k
    amazon-ebs: httpd-tools   x86_64 2.2.31-1.7.amzn1
    amazon-ebs: amzn-main  79 k
    amazon-ebs:
    amazon-ebs: Transaction Summary
    amazon-ebs: ========================================
    amazon-ebs: Install  1 Package (+4 Dependent packages)
    amazon-ebs:
    amazon-ebs: Total download size: 1.5 M
    amazon-ebs: Installed size: 3.6 M
    amazon-ebs: Downloading packages:
    amazon-ebs: (1/5): apr-1.5.1 | 116 kB     00:00
    amazon-ebs: (2/5): apr-util- |  87 kB     00:00
    amazon-ebs: (3/5): apr-util- |  17 kB     00:00
    amazon-ebs: (4/5): httpd-2.2 | 1.2 MB     00:00
    amazon-ebs: (5/5): httpd-too |  79 kB     00:00
    amazon-ebs: ----------------------------------------
    amazon-ebs: Total      5.0 MB/s | 1.5 MB  00:00
    amazon-ebs: Running transaction check
    amazon-ebs: Running transaction test
    amazon-ebs: Transaction test succeeded
    amazon-ebs: Running transaction
    amazon-ebs:   Installing : apr-1.5.1-1.12.amz   1/5
    amazon-ebs:   Installing : apr-util-1.4.1-4.1   2/5
    amazon-ebs:   Installing : apr-util-ldap-1.4.   3/5
    amazon-ebs:   Installing : httpd-tools-2.2.31   4/5
    amazon-ebs:   Installing : httpd-2.2.31-1.7.a   5/5
    amazon-ebs: Verifying  : httpd-2.2.31-1.7.a   1/5
    amazon-ebs: Verifying  : apr-1.5.1-1.12.amz   2/5
    amazon-ebs: Verifying  : apr-util-ldap-1.4.   3/5
    amazon-ebs: Verifying  : httpd-tools-2.2.31   4/5
    amazon-ebs: Verifying  : apr-util-1.4.1-4.1   5/5
    amazon-ebs:
    amazon-ebs: Installed:
    amazon-ebs: httpd.x86_64 0:2.2.31-1.7.amzn1
    amazon-ebs:
    amazon-ebs: Dependency Installed:
    amazon-ebs: apr.x86_64 0:1.5.1-1.12.amzn1
    amazon-ebs: apr-util.x86_64 0:1.4.1-4.17.amzn1
    amazon-ebs: apr-util-ldap.x86_64 0:1.4.1-4.17.amzn1
    amazon-ebs: httpd-tools.x86_64 0:2.2.31-1.7.amzn1
    amazon-ebs:
    amazon-ebs: Complete!
==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating the AMI: test-amzn-all-1458682583415-amzn
    amazon-ebs: AMI: ami-3eaf2b4d
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Adding tags to AMI (ami-3eaf2b4d)...
    amazon-ebs: Adding tag: "appversion": ""
    amazon-ebs: Adding tag: "build_host": ""
==> amazon-ebs: Tagging snapshot: snap-43456d59
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

eu-west-1: ami-3eaf2b4d
```

**Comment by radkin** [comment]
Added the changes from this merge to my dev instance and it was able to successfully bake & deploy CentOS to GCP using these packer changes.

**Comment by gardleopard** [comment]
Thanks for testing @radkin! Great that it worked out for you.

**Comment by duftler** [comment]
Thanks @radkin and @gardleopard for all your work on this.

**Pull request merged**
