### PR TITLE
fix(bakeManifest): helm --set option

### PR DESCRIPTION
**Pull request by ethanfrogers**
adds an option to toggle between `--set` and `--set-string`. we recently
had to revert a commit which changed `--set-string` to `--set` and
introduced a breaking change. this keeps the default behavior of
`--set-string` but allows users to choose which option they want to use.

### CODE REVIEW

**Comment by maggieneterval** [comment]
@ethanfrogers are there corresponding Orca/Deck PRs for configuring thist option? Also curious if you think there will ever potentially be options besides `--set` and `--set-string` and we should use an enum rather than a boolean here?

**Comment by ezimanyi** [comment]
It looks like this is only going to be a top-level option for the entire manifest bake---will this work for people who want to set both integers and booleans as overrides?  I'm wondering if we should think about a solution that will work for that case, as it will be more confusing to implement a solution to that case if we already have a top-level toggle between set and set string for the entire stage.

**Comment by ethanfrogers** [comment]
@ezimanyi I share the same concern. However, I think we have a couple of options. 

1. If we want to add two separate sections we could toggle off of this property and fill out the appropriate section (overrides or rawOverrides) in the UI. 
2. We could move to a more complex data structure to represent each individual value (key, value, raw|string), which I think would be possible, given the current data structure (`Map<String, Object>).

Either way, I think we can _safely_ transition to either one, using this value to determine the type of override, at least in the UI. 

Either way, we'll have to support backwards compatibility

**Comment by ethanfrogers** [comment]
@spinnakerbot 🍒 ⛏ 1.16

**Comment by ethanfrogers** [comment]
@spinnakerbot cherry-pick 1.16

**Pull request merged**
