### PR TITLE
fix(Azure): Update centos default image version.

### PR DESCRIPTION
**Pull request by DanielaS12**
Centos 7.1 is no longer available for Azure

### CODE REVIEW

**Comment by ovidiupopa07** [comment]
closes https://github.com/spinnaker/spinnaker/issues/6763

**Review by ovidiupopa07 — APPROVED** [review]

**Comment by nemesisOsorio** [comment]
can you please add a couple of print screens to check if the scripts are compatible with this image?

**Comment by DanielaS12** [comment]
Package is installed
image

LOGS
image

Pipeline is green
image

**Comment by nemesisOsorio** [comment]
nvm here is the tests
image
we created a vm and verifying git was installed
image

**Review by nemesisOsorio — APPROVED** [review]

**Review by dogonthehorizon — APPROVED** [review]

**Pull request merged**
