### PR TITLE
Fix aws enhanced networking backwards incompatibities 2

### PR DESCRIPTION
**Pull request by ikemonn**
@duftler 
This is new PR of https://github.com/spinnaker/rosco/pull/225

refs https://github.com/spinnaker/spinnaker/issues/2065

### CODE REVIEW

**Comment by duftler** [comment]
Still looks to need a rebase. Several ways to do this, but I typically fetch upstream master locally and then squash commits and rebase my branch onto master before pushing to github.

Is the commit just prior to your new commit the same as is at head of upstream?

**Comment by ikemonn** [comment]
@duftler 
Sorry to bother you again. 
I executed the following command.
Is this right?
If I made a mistake, could you please tell me git command?

```
git checkout master
git remote add upstream git@github.com:spinnaker/rosco.git
git fetch upstream
git checkout fix_aws_enhanced_networking_backwards_incompatibities_2
git merge upstream/master
git rebase -i HEAD~2
git push -f origin fix_aws_enhanced_networking_backwards_incompatibities_2
```

**Comment by duftler** [comment]
The end result looks right to me.

**Comment by ikemonn** [comment]
Thanks!

**Comment by duftler** [comment]
Thanks for the fix.

**Pull request merged**
