### PR TITLE
chore(kustomize): add git and openssh clients

### PR DESCRIPTION
**Pull request by rojopolis**
This adds git and openssh clients to rosco images to accommodate the use cases described here: https://github.com/spinnaker/spinnaker/issues/4703#issuecomment-572938366

### CODE REVIEW

**Comment by kaidotdev** [comment]
Any update?

**Comment by ethanfrogers** [comment]
@rojopolis - I can't update this branch for some reason. Would you mind updating it on your side? Once the build passes, I'll merge it.

**Comment by rojopolis** [comment]
> @rojopolis - I can't update this branch for some reason. Would you mind updating it on your side? Once the build passes, I'll merge it.

Done.
@ethanfrogers

**Comment by TamirHAhmed** [comment]
hmm any update on when this would be merged? :smile:

**Comment by kaidotdev** [comment]
I'm looking forward to it, too.
@ethanfrogers

**Comment by rverma-jm** [comment]
i think with this we should increase the default okhttp connection timeout too. Since with git fetching 20ms is too less.

**Comment by rverma-jm** [comment]
Can we please get this PR merged?

**Comment by ethanfrogers** [comment]
@rverma-jm - if you wouldn't mind resolving the conflicts we can try to get this merged today!

**Comment by rojopolis** [comment]
> @rverma-jm - if you wouldn't mind resolving the conflicts we can try to get this merged today!

Done (again).

**Comment by ethanfrogers** [comment]
| Done (again).
Apologies. My priorities have shifted as of late and I've had less time to review and focus on these PRs. Thanks for updating!

**Pull request merged**
